ARG COTURN_VERSION=4.6.3
FROM coturn/coturn:${COTURN_VERSION}

LABEL org.opencontainers.image.title="Love Home coturn" \
      org.opencontainers.image.description="Multi-architecture coturn image for Love Home"
